ghostunnel/ghostunnel

.travis.yml
Makefile
README.md
net.go
signals.go
tests/test-reloads-certificate.py
tests/test-reloads-root-certificate.py
tests/test_common.py
tls.go
watcher.go
watcher_test.go

Add Travis-CI config

---

README.md
main.go
tests/test-reloads-certificate.py
tests/test-reloads-root-certificate.py
watcher.go
watcher_test.go

Remove auto-reload functionality. Doesn't work well in practice, let's remove it in favor of the timed reload functionality (and manual reload via `SIGUSR1`).
r: @alokmenghrajani

Remove auto-reload functionality

---

README.md

Show build status on master

---

tests/test_common.py

Dump generated test keys for better debugability
r: @alokmenghrajani

Dump generated test keys for better debugability

---

main.go

Support profiling via --pprof flag
r: @alokmenghrajani

Support profiling via --pprof flag

---

tests/test_common.py

Cleaner integration testing output, make timeouts consistent.

Cleaner integration testing output

---

.travis.yml
Makefile
main.go
status.go

Better flag handling, expose revision/compiler in status. Also fixes some lints.

Better flag handling, expose revision/compiler in status

---

main.go
metrics.go
signals.go
status.go
test-keys/openssl.ext
tests/openssl.ext
tests/test-metrics-bridge.py
tests/test-status-port.py

Changes:
- Support status port listening on more than just localhost (if specified)
- Status port should listen using TLS certificates (HTTPS, not just HTTP)

Status port changes

---

.travis.yml

Build on Go tip, allow failures

Build on Go tip

---

Makefile

Use git describe instead of rev-parse for version output

Use git describe instead of rev-parse for version output

---

main.go
tests/test-metrics-graphite.py

Changes:
* Use sane graphite arguments
* Log if/where metrics enabled
* Add integration test for graphite support

Better graphite support

---

main.go
tls.go
tls_test.go

Support configurable min TLS version
r: @stouset

Support configurable min TLS version

---

.gitignore
.travis.yml
Makefile
glide.lock
glide.yaml

Vendor dependencies, using Go 1.5's vendor experiment flag and Glide.
r: @alokmenghrajani @mcpherrinm

Vendor dependencies

---

README.md

r: @alokmenghrajani @mcpherrinm

Add notes about building to readme

---

README.md

@alokmenghrajani 
Add note about glide to readme

Add note about glide to readme

---

main.go
metrics.go

r: @alokmenghrajani @mcpherrinm 
Collect memory usage metrics

Collect memory usage metrics

---

metrics.go

r: @alokmenghrajani 
Fix leak of response body

Fix leak of response body

---

.travis.yml
README.md
auth_test.go
metrics.go

Build on Go 1.6, run gofmt -s to simplify some code, add go report card badge.

Clean up some nits

---

main.go

r: @alokmenghrajani @mcpherrinm 
Fix flag validation to work with --allow-dns-san, --allow-ip-san

Fix flag validation to work with --allow-dns-san, --allow-ip-san

---

.travis.yml
Makefile
tests/test-metrics-bridge.py
tests/test-metrics-graphite.py
tests/test-min-tls-flag.py
tests/test-reloads-certificate.py
tests/test-reloads-root-certificate.py
tests/test-status-port.py
tests/test_common.py

r: @alokmenghrajani @mcpherrinm 
Add test for --min-tls flag

Add test for --min-tls flag

---

tests/openssl.ext
tests/test-server-concurrent-connections.py
tests/test-server-handles-client-closes-connection.py
tests/test-server-handles-no-server.py
tests/test-server-handles-server-closes-connection.py
tests/test-server-metrics-bridge.py
tests/test-server-metrics-graphite.py
tests/test-server-min-tls-flag.py
tests/test-server-rejects-invalid-ou-or-ca.py
tests/test-server-reloads-certificate.py
tests/test-server-reloads-root-certificate.py
tests/test-server-status-port.py
tests/test-server-unix-socket-backend.py
tests/test_common.py

No more manual cleanup! Some other minor changes too.

Improve code to create/cleanup test certs.

---

README.md

Add version info to readme

---

README.md
auth.go
auth_test.go
docker/redis-tls/entry.sh
main.go
main_test.go
tests/test-server-concurrent-connections.py
tests/test-server-handles-client-closes-connection.py
tests/test-server-handles-no-server.py
tests/test-server-handles-server-closes-connection.py
tests/test-server-metrics-bridge.py
tests/test-server-metrics-graphite.py
tests/test-server-min-tls-flag.py
tests/test-server-rejects-invalid-ou-or-ca.py
tests/test-server-reloads-certificate.py
tests/test-server-reloads-root-certificate.py
tests/test-server-status-port.py
tests/test-server-unix-socket-backend.py

Prepares for a client subcommand. Move server related options into the subcommand.

Add server subcommand.

---

README.md
main.go
main_test.go
net.go
net_test.go
signals.go
tests/test-client-concurrent-connections.py
tests/test-client-handles-client-closes-connection.py
tests/test-client-handles-no-server.py
tests/test-client-handles-server-closes-connection.py
tests/test-client-metrics-bridge.py
tests/test-client-metrics-graphite.py
tests/test-client-min-tls-flag.py
tests/test-client-rejects-invalid-san-or-ca.py
tests/test-client-reloads-certificate.py
tests/test-client-status-port.py
tests/test-client-unix-socket-backend.py
tests/test-server-handles-no-server.py
tests/test-server-min-tls-flag.py
tests/test_common.py

ghostunnel listens on localhost:port and forwards connections to a remote server using mutual TLS.

Add support for "client" mode.

---

main.go
net.go
net_test.go

r: @alokmenghrajani 
Fixes various nits, found via `gometalinter`.

Fix various nits

---

README.md
main.go
net.go
net_test.go

This can be squished or whatever.
* spelling: probably
* spelling: given (I'm less certain about this one)
* spelling: forward
* spelling: daemonization
* spelling: connection

spelling fixes

---

main.go
tests/test-client-override-server-name.py

Add --override-server-name option for client

---

Makefile
main.go
main_test.go
net.go
net_test.go
signals.go
status.go
status_test.go
tests/test-client-auto-reload-certificate.py
tests/test-client-override-server-name.py
tests/test-client-reload-broken-certificate.py
tests/test-server-auto-reload-certificate.py
tests/test-server-metrics-bridge.py
tests/test-server-reload-broken-certificate.py
tests/test_common.py
tls.go
tls_test.go

Adds lots of extra testing, bumps up test coverage, fixes a couple of bugs I found.
Updated coverage info: https://coveralls.io/builds/5296524

Extra testing, fix some nits

---

main.go
main_test.go

Add more tests, particularly for some errors conditions from stuff in main.go.

Add more tests

---

tls.go
tls_test.go

Simplify keystore parsing

---

.travis.yml
README.md
tests/test_common.py

Drop unused pyOpenSSL dependency

Drop unused pyOpenSSL dependency

---

main.go
tests/test-client-unix-socket-backend.py
tests/test-server-unix-socket-backend.py

r: @stouset 
Clean up UNIX sockets on shutdown

Clean up UNIX sockets on shutdown

---

Dockerfile
docker/redis-tls/entry.sh

Use chain-exec functionality in redis-tls dockerfile

Use chain-exec functionality in redis-tls dockerfile

---

glide.lock
main.go
tests/test-client-auto-reload-certificate.py
tests/test-client-metrics-bridge.py
tests/test-client-metrics-graphite.py
tests/test-client-override-server-name.py
tests/test-server-auto-reload-certificate.py
tests/test-server-metrics-bridge.py
tests/test-server-metrics-graphite.py

@mcpherrinm @sqshh @alokmenghrajani

Configurable metrics publishing interval

---

.travis.yml
README.md
main.go
tls.go
tls_test.go

Use system roots if ca-bundle not specified

Use system roots if ca-bundle not specified

---

main.go

Log client/server listen errors

Log client/server listen errors

---

main.go

Add some more error logging (through logger)

Add some more error logging (through logger)

---

.travis.yml
tests/test-server-pkcs11-module.py

Add integration tests for PKCS11 support, via SoftHSM.

Add integration tests for PKCS11 support

---

.travis.yml

Build with Go 1.9 in Travis-CI

Build with Go 1.9 in Travis-CI

---

net.go

Add timer to measure handshake latency. Tells us how fast handshakes are performed based on runtime data. Useful to measure the performance of PKCS#11 tokens.

Add timer to measure handshake latency

---

.travis.yml

Add more builds in Travis-CI, plus upload sha256sum of release builds

Add more builds in Travis-CI

---

auth.go
auth_test.go
main.go
net.go
signals.go
status.go
watcher_test.go

Fix minor nits found via gometalinter. Adds some error checks, logging, and adds buffering to the signal receive channel.

Fix minor nits (found via gometalinter)

---

.appveyor.yml

Only install necessary deps in AppVeyor build

Only install necessary deps in AppVeyor build

---

.appveyor.yml
CONTRIBUTING.md
CROSS-COMPILE.md
Makefile
README.md
signals.go

Adds some docs, removes a bit of duplicated code

Some small fixes and things

---

.appveyor.yml
.travis.yml
CROSS-COMPILE.md

Build Windows releases in Travis-CI (through karalabe/xgo)

Build Windows releases in Travis-CI (through karalabe/xgo)

---

.appveyor.yml
auth/auth_test.go
main.go
tls.go

* Add an extra test for the auth package
* Simplify the server flag validation a bit
* Check timeout flag value (timeouts can't be zero)

Extra test & flag checks

---

.travis.yml
Dockerfile

Fix Docker image, ghostunnel needs libtool runtime dep to run if compiled with CGO_ENABLED=1.

Fix Docker image

---

Dockerfile
auth/auth.go
auth/auth_test.go
main.go
net.go
signals.go
tls_test.go
watcher_test.go

Fix some nits (found via gometalinter), update Go version in Dockerfile.

Fix some nits, update Go version in Dockerfile

---

.travis.yml
Dockerfile
Makefile.dist
README.md

Bump build(s) to Go 1.11

---

Makefile
tests/test-client-verify-dns-san.py
tests/test-client-verify-uri-san.py
tests/test-server-allow-dns-san.py
tests/test-server-allow-uri-san.py

Add tests for {allow,verify}-{dns,uri} flags

Add tests for {allow,verify}-{dns,uri} flags

---

.travis.yml
Dockerfile
Makefile.dist

Build with Go 1.12

---

main.go
main_test.go
proxy/proxy.go
proxy/proxy_test.go
tests/common.py
tests/test-client-handles-client-closes-connection-unix.py
tests/test-client-handles-server-closes-connection-unix.py
tests/test-server-allow-uri-san.py
tests/test-server-handles-client-closes-connection-unix.py
tests/test-server-handles-server-closes-connection-unix.py
tests/test-server-quiet-all-logs.py
tests/test-server-quiet-conn-logs.py

Cleaner logging for proxy module

---

.travis.yml
Dockerfile
Makefile.dist
README.md

Bump build to Go 1.12.4

---

main.go

Changes from #243, plus small refactor I added. cc @mblaschke

Fix unsafe cipher validation

---

main.go

For issue #249, cc @satheeshaGowda

Expose keystore flags as env vars

---

.travis.yml
Dockerfile
Makefile.dist
README.md

Bump up to the latest release.

Update to Go 1.13.3

---

certloader/certigo_test.go
certloader/certstore_enabled.go
main.go
proxy/proxy_test.go

I also encountered some changes to `go.mod` and `go.sum` but figured this was not the right PR for those.

Minor style fixes

---

certloader/no_cert_test.go
proxy/proxy_test.go
tls_test.go

Just some issues that I found on [Go Report Card](https://goreportcard.com/report/github.com/square/ghostunnel#ineffassign). 
Let me know if they're not necessary or the messages aren't quite right, happy to close it out or modify as needed.

Some "ineffassign" fixes

---

docs/METRICS.md

Add HTTP status port exposing on METRICS.md

---

docs/ACCESS-FLAGS.md

Correct CN --> OU in server mode ACCESS-FLAGS doc (--allow-ou).

Correct CN --> OU in ACCESS-FLAGS DOC

---

.github/workflows/release.yml
.github/workflows/test.yaml
README.md
tests/test-client-concurrent-connections.py
tests/test-server-concurrent-connections.py
tests/test-server-status-port-unix.py

Run integration tests on macOS using actions

Run integration tests on macOS using actions

---

.github/workflows/test.yaml

Upload coverage to Codecov

---

main.go
socket/net.go
socket/net_test.go
tests/test-client-via-http-connect-proxy.py

Better connect proxy resolve handling as a follow-up to #357. Fixes issue #355.

Better connect proxy resolve handling

---

.github/workflows/release.yml
.github/workflows/test.yml
README.md

Switch to Go 1.19.1

---

auth/auth.go
auth/auth_test.go
main.go
policy/loader.go
policy/loader_test.go
policy/policy.go
policy/wrap.go
policy/wrap_test.go
signals.go
status.go
tests/common.py
tests/test-allow-all.rego
tests/test-client-invalid-opa.py
tests/test-client-verify-opa.py
tests/test-server-allow-opa.py
tests/test-server-invalid-opa.py
tests/test-server-opa-reload-fail.py

Reload OPA policy files on disk during reloading

Reload OPA policy files on disk during reloading

---

.github/workflows/compile.yml
.github/workflows/release.yml
.github/workflows/test.yml

Cross-compile for ARM64 platforms

Cross-compile for darwin/arm64

---

.github/workflows/release.yml

Add .exe extension to windows release artifacts

---

.github/workflows/compile.yml
.github/workflows/release.yml

Closes #400.
(I really just did copy/paste, I don't know if that is okay/enough).

Release arm64 binary for Linux.

---

.github/workflows/compile.yml
.github/workflows/release.yml
.github/workflows/test.yml
certloader/spiffe_tls_config.go
certloader/spiffe_tls_config_test.go
main.go
vendor/github.com/spiffe/go-spiffe/v2/spiffetls/tlsconfig/config.go

Avoid setting GetCertificate for SPIFFE in client mode if auth is disabled

---

.github/workflows/test.yml

Add CODECOV_TOKEN as env var

---

landlock_linux.go
landlock_test.go

Some flags can contain both a host:port address as well as a URL starting with http(s)://. For example, the status flag can contain a host:port to serve status on HTTPS by default. But it can also explicitly contain an HTTP URL to disable HTTPS.
To accommodate flags containing both possible values, we combine the parsing into one function and look at the http(s):// prefix to see if we're dealing with a URL instead of a host:port.

Better landlock rule processing

---

.github/workflows/docker.yml

Fix Docker image build workflow for release

Fix Docker image build workflow for release

---

tests/common.py
tests/test-client-handles-client-closes-connection-unix.py
tests/test-client-handles-client-closes-connection.py
tests/test-client-handles-server-closes-connection-unix.py
tests/test-client-handles-server-closes-connection.py
tests/test-server-handles-client-closes-connection-unix.py
tests/test-server-handles-client-closes-connection.py
tests/test-server-handles-server-closes-connection-unix.py
tests/test-server-handles-server-closes-connection.py

Add a bit more logic to half-close tests

Add a bit more logic to half-close tests

---

README.md

Fix manpage link
