- .travis.yml
- main.go
- signals.go
- status.go
Support for optionally serving /_status endpoint. Closes #23.
Example response from status handler:
```
{"ok":false,"status":"critical","backend_ok":false,"backend_status":"critical","backend_error":"dial tcp4 127.0.0.1:8080: getsockopt: connection refused",message:"listening","time":"2015-12-15T19:52:17.050538029-08:00","hostname":"cs.local"}
```
> Support for optionally serving /_status endpoint

- main.go
- status.go
* Make status port listen on localhost only
* Use SO_REUSEPORT to allow co-existent tunnels (for in-place upgrades)
* Return 503 on /_status if tunnel down (see https://github.com/square/p2/wiki/Health-Checks)
> Status improvements

- tls.go
Changes to cipher suites:
- drop AES-256, it's unnecessary
- allow ECDSA instead of just RSA
r: @stouset @alokmenghrajani
> Update cipher suites to allow ECDSA, drop AES-256

- .travis.yml
- main.go
Avoid tls.Config object copy (has embedded lock)
Fixes go vet error:
```
cs ghostunnel master $ go vet ./...
main.go:266: serveStatus passes Lock by value: crypto/tls.Config contains sync.Once contains sync.Mutex
exit status 1
```
> Avoid tls.Config object copy (has embedded lock)

- README.md
- docker/redis-tls/Dockerfile
- docker/redis-tls/README.md
- docker/redis-tls/run.sh
Dockerfile for redis with ghostunnel. Serves as an example for how to secure services that do not natively support SSL/TLS by fronting them with ghostunnel.
> Dockerfile for redis with ghostunnel

- .travis.yml
- Makefile
- tests/test-concurrent-connections.py
- tests/test-handles-client-closes-connection.py
- tests/test-handles-no-server.py
- tests/test-handles-server-closes-connection.py
- tests/test-metrics-bridge.py
- tests/test-metrics-graphite.py
- tests/test-rejects-invalid-ou-or-ca.py
- tests/test-reloads-certificate.py
- tests/test-reloads-root-certificate.py
- tests/test-status-port.py
- tests/test-unix-socket-backend.py
- tests/test_common.py
r: @alokmenghrajani 
Runs tests with Python 3 (using Travis-CI's "Trusty Tahr" image). This will make it possible to properly test the --min-tls flag in our integration tests (since we get TLS 1.2 support).
> Run tests with python 3

- .travis.yml
- Dockerfile
- docker/redis-tls/Dockerfile
- docker/redis-tls/entry.sh
@alokmenghrajani @mcpherrinm 
Changes:
* Split ghostunnel build into separate dockerfiles
* Simplify redis-tls dockerfile (install redis from alpine instead of tarball)
* Build docker images on travis-ci runs
Also dropped Go 1.5 and tip from build. We don't need to support Go 1.5 anymore, and Go tip is continuously broken anyway which makes it kinda useless. Speeds up the build.
> Split dockerfiles

- README.md
- glide.lock
- main.go
@alokmenghrajani @mcpherrinm @sqshh 
Some small changes:
* Use TLSv1.2 as default now that we have TLSv1.2 support on Travis-CI
* Update some flag descriptions to be more accurate (e.g. mention UNIX sockets)
* Upgrade to new kingpin version, provides bash/zsh completion support
To get completion in your shell, e.g. zsh:
eval "$(ghostunnel --completion-script-zsh)"
> Small changes

- .gitignore
- .travis.yml
- Makefile
- README.md
- main.go
- main_test.go
- tests/test-client-concurrent-connections.py
- tests/test-client-handles-client-closes-connection.py
- tests/test-client-handles-no-server.py
- tests/test-client-handles-server-closes-connection.py
- tests/test-client-metrics-bridge.py
- tests/test-client-metrics-graphite.py
- tests/test-client-override-server-name.py
- tests/test-client-rejects-invalid-san-or-ca.py
- tests/test-client-reloads-certificate.py
- tests/test-client-status-port.py
- tests/test-client-unix-socket-backend.py
- tests/test-server-concurrent-connections.py
- tests/test-server-handles-client-closes-connection.py
- tests/test-server-handles-no-server.py
- tests/test-server-handles-server-closes-connection.py
- tests/test-server-metrics-bridge.py
- tests/test-server-metrics-graphite.py
- tests/test-server-rejects-invalid-ou-or-ca.py
- tests/test-server-reloads-certificate.py
- tests/test-server-reloads-root-certificate.py
- tests/test-server-status-port.py
- tests/test-server-unix-socket-backend.py
- tests/test_common.py
r: @alokmenghrajani @mcpherrinm 
Generate test coverage for integration tests. This pull request changes our integration test suite to run ghostunnel through an integration test hook in `main_test.go`, so that we can record coverage information for the external tests we run. Also adds a badge to the repo to show coverage.
Inspiration from: https://www.elastic.co/blog/code-coverage-for-your-golang-system-tests
Coverage information here: https://coveralls.io/github/square/ghostunnel
> Generate test coverage for integration tests

- README.md
Was referring to CN/OU, but we also support SAN checks.
> Fix readme wording

- .travis.yml
- Makefile
- README.md
- main.go
- status.go
- tests/test_runner.py
Simplifies the make file, changes the way we run integration tests. In particular, only print stdout/stderr from integration tests if they fail. Otherwise just print "PASS" and move on. Also prints time taken per test.
> Simplify build scripts

- main.go
- net.go
- tests/test-server-tls-handshake-timeout.py
- tests/test_common.py
r: @alokmenghrajani @mcpherrinm @stouset 
Avoid blocking whenever possible:
* we time out when dialing backend connections (both in client and server mode)
* we time out if a TLS handshake is taking too long (forcibly kill via deadline)
* perform handshake in background routine to not block accept loop
> Timeouts for backend connections, handshakes.

- README.md
Noticed a really minor typo in the README as I was looking up an example.
> Fixes tiny typo in client mode example

- .travis.yml
- main.go
- main_test.go
- net.go
- status.go
- status_test.go
- tests/test-client-chain-exec-error.py
- tests/test-client-chain-exec-success.py
- tests/test-server-chain-exec-enoent.py
- tests/test-server-chain-exec-error.py
- tests/test-server-chain-exec-success.py
- tests/test_common.py
Support for chaining execution of a subprocess. Makes it easier to coordinate processes.
For example, can now wrap a child command like:
ghostunnel server [FLAGS] -- redis-server
Launches the given command on startup before listening. If the child process exits, the tunnel also exits along with it. Prevents stale tunnels from hanging around after their backend has terminated, and makes sure a process manager above us notices that we're shut down and can restart appropriately.
> Initial chain-exec support

- main.go
- signals.go
- tests/test-client-shutdown-sigterm.py
- tests/test-server-shutdown-sigterm.py
@alokmenghrajani @mcpherrinm @sqshh
Fix behavior of multiple SIGTERM on client: if we receive multiple SIGTERM signals, the client should always shut down. To do so, we unregister the signal handler for SIGTERM before exiting the client signal handler function. Also, this adds a hard timeout of 5 minutes for graceful shutdown after which we terminate even if there are still open connections.
> Fix behavior of multiple SIGTERM on client

- Makefile
- main.go
- main_test.go
- signals.go
- tests/test-server-status-port-unix.py
- tests/test_common.py
Changes to allow status port to be a UNIX socket via `--status=unix:PATH` (instead of just `HOST:PORT`).
This is useful in cases where we don't want to listen on _yet another_ port on a host.
To connect, just use curl:
```
$ curl -s --unix-socket /tmp/ghostunnel-status.sock http:/_status | jq .
{
"ok": true,
"status": "ok",
"backend_ok": true,
"backend_status": "ok",
"child_pid": 40486,
"time": "2016-04-30T19:39:01.5509053-07:00",
"hostname": "carbon",
"message": "listening",
"revision": "v1.0.2-1-g930874df",
"compiler": "go1.6"
}
```
> Allow status port to be a UNIX socket

- main.go
- main_test.go
- signals.go
- tests/child-process-sigterm-trap.py
- tests/test-server-chain-exec-shutdown-timeout.py
Previously, when ghostunnel would hit the graceful shutdown timeout, it would simply exit without signaling to the child process. This changes the logic to make sure we always terminate the child on exit. In addition, we also add a test to make sure that a misbehaving child which is ignoring SIGTERM is properly killed after timeout.
> Terminate child on exit timeout

- README.md
> Fix double wording in readme

- README.md
- main.go
- tls.go
Changes:
* Use P-256 as the only allowable curve, as it is the only one that has an ASM implementation. 
* Mention that we only support x86-64 (other platforms don't have any constant-time curves).
* While we're at it, bump version for next release (1.0.6, we accidentally skipped 1.0.5).
> Use P-256 as only allowable curve

- main.go
- tests/test-client-via-http-connect-proxy.py
- tls.go
- vendor/github.com/mwitkow/go-http-dialer/LICENSE
- vendor/github.com/mwitkow/go-http-dialer/auth.go
- vendor/github.com/mwitkow/go-http-dialer/dialer.go
- vendor/manifest
Add HTTP CONNECT proxy support to ghostunnel. Set the new connect-proxy flag and ghostunnel will establish TCP connections through the proxy instead of directly.
> Add HTTP CONNECT proxy support

- main.go
- procattr_generic.go
- procattr_linux.go
- signals.go
- tests/child-process-sigterm-trap.py
- tests/child-process-waits-forever.py
- tests/test-server-shutdown-sigchld.py
Better process management:
* When executing child process, create new process group. This allows us to send signals to all child processes instead of just our direct descendant.
* Set Pdeathsig on Linux to send SIGTERM to child if ghostunnel exists. This avoids child processes being orphaned in case of e.g. a bug in ghostunnel that causes it to exit without terminating the child process. 
* Signal handler to forward signals to child process group. If ghostunnel receives a SIGTERM, we forward and send SIGTERM to child process group to tell it to shut down. 
* Handle SIGCHLD in main signal handler, to get ghostunnel to shut down if the child exits. Previously ghostunnel was just blocking on waitpid() and ignoring SIGCHLD. 
Note that this doesn't clean up any processes that are orphaned and …
> Better process management

- .travis.yml
- README.md
- main.go
- tls.go
- tls_cgo.go
- tls_no_cgo.go
- tls_test.go
This makes the build pass with CGO_ENABLED=0.
With CGO enabled, I can't compile on android.  Since I don't need PKCS11
here, I figure this is a reasonable alternative.
This PR isn't done -- opening so I can get some Travis builds to make sure it still works with CGO.
> [WIP] Disable PKCS11 without CGO

- .travis.yml
- Dockerfile
- Dockerfile-test
- Makefile
- README.md
Adds `Dockerfile-test` which builds a base image for running Ghostunnel integration tests, including PKCS11 tests via SoftHSM. This makes the integration tests a bit more predictable and allows for running them locally without having to set up SoftHSM and such. Also takes some complexity out of the Travis-CI build file and puts it into the Dockerfile.
> Run integration tests in Docker

- Dockerfile-test
- Makefile
Clean before running integration tests in docker. Avoids failures from switching back and forth between running tests locally on a mac and running them in docker/linux.
> Clean before running integration tests in docker

- main.go
- tests/test-server-status-port-unix.py
- tls.go
* Validate that the schema of connect-proxy is http/https (http_dialer is unhappy otherwise)
* Improve logging a big, show source/target/proxy addresses and certificate info in the log output
* Don't log cipher suites in `buildConfig` because it gets called multiple times and duplicates the output
> Better logging and flag validation

- main.go
- main_test.go
Better error handling for syslog failures, to make unit tests run in containers (or container-based IDEs like c9.io) without having to run/bind syslog somewhere.
> Better error handling for syslog failures

- main.go
The `handlers` waitgroup looks as though it was copy/pasted along with some other code during a previous change, but the actual waitgroup was moved to the proxy instance.
> Removing a waitgroup that is not used

- .appveyor.yml
- .gitignore
- .travis.yml
- main.go
- main_test.go
- signals.go
- signals_unix.go
- signals_windows.go
- status_test.go
- tls_cgo.go
- tls_no_cgo.go
- tls_test.go
- vendor/github.com/hashicorp/go-syslog/LICENSE
- vendor/github.com/hashicorp/go-syslog/builtin.go
- vendor/github.com/hashicorp/go-syslog/syslog.go
- vendor/github.com/hashicorp/go-syslog/unix.go
- vendor/github.com/hashicorp/go-syslog/unsupported.go
- vendor/manifest
Changes to support Windows platforms:
* Use a wrapper package for `log/syslog` to fix import errors
* Update signal handling to work on Windows (signal-initiated reload not supported)
In action:
Tested 32-bit and 64-bit compile with PKCS11 disabled, and 32-bit compile with PKCS11 enabled (via MinGW/GCC). I have not tested an actual instance of Ghostunnel running with a PKCS11 module loaded on a Windows box, so no guarantees that that works right now.
> Basic Windows support

- Dockerfile-test
- Makefile
- main.go
- main_test.go
- tests/test-server-pkcs11-module.py
- tls_cgo.go
- unix.go
- windows.go
* Skip syslog flag on Windows, since it's not supported.
* Add env vars for PKCS11 flags so PIN can be in env var if desired.
> Flag cleanup

- auth.go
- auth_test.go
- main.go
- main_test.go
- net.go
- signals.go
- tests/test-invalid-cacert.py
- tests/test-invalid-certificate.py
- tests/test-invalid-client-flags.py
- tests/test-invalid-server-flags.py
- tls.go
- tls_test.go
Changes to make only main read flags directly, otherwise have them passed as arguments. Add some extra test cases related to flag handling.
> Only refer to flags in main, add extra tests for invalid flags

- .gitignore
- .travis.yml
- Makefile
- Makefile.dist
- README.md
Continuation of #154:
* Hook Makefile.dist into Travis-CI
* Skip compression of artifacts since it's just one file per arch
* Use karalabe/xgo again to get cross-compile with PKCS11 (CGO must be enabled)
* Skip builds for BSD platforms since it's not supported by xgo at the moment
* Skip 386 build for linux/darwin (shouldn't bother with 32-bit on those platforms)
In effect, this builds linux/amd64, darwin/amd64, windows/{386,amd64} (with 5.1 API level).
> Add Makefile.dist for release binaries in Travis-CI

- CROSS-COMPILE.md
- Makefile
- Makefile.dist
- README.md
- main.go
Set version through ldflags, via Makefile.dist, so we don't have to manually bump the version global anymore.
> Set version through ldflags

- main.go
Because ghostunnel's usage is relatively compact and most useful params are on
a subcommand, default to long help
> Default to long help.

- main.go
Fixes a bug you encounter when you run:
```
$ ./ghostunnel server --listen localhost:8443 --target localhost:8080 --disable-authentication
[5392] 2018/03/30 14:14:19.039912 starting ghostunnel in server mode
one of --keystore or --disable-authentication is required, try --help
```
The current code base checks `(*keystorePath == "") && !(*clientDisableAuth)` in all modes, server or client. Moved the check to inside the client checks.
> Ghostunnel without authentication

- Dockerfile
Use a multi-stage build to make the resulting image smaller, and not require
cleanup to be done.
Explicitly use versioned release to avoid problems with folks having older
versions of golang:alpine.
Move dep install ahead of the source COPY so we get better caching.
> Update dockerfile: Multistage build with go1.10.1

- README.md
Improve the docs for PKCS11 a bit, adds some examples for how to use pkcs11-tool to list slots or read certificates from a token since ghostunnel can't directly read certs off of the module right now.
> Add some more info about PKCS11 modules

- .appveyor.yml
- Makefile
- auth/auth.go
- auth/auth_test.go
- certloader/keystore_test.go
- main.go
- wildcard/matcher.go
- wildcard/matcher_test.go
This implements simple pattern matching so that the `allow-uri` flag can take patterns like:
* `spiffe://a/*/c`
* matches e.g. `spiffe://a/b/c` or `spiffe://a/b/c/`
* `spiffe://a/b/**`
* matches e.g. `spiffe://a/b/c` or `spiffe://a/b/c/d/e`
The wildcard `*` matches any char except a forward slash, and can appear between any two slashes. The wildcard `**` can only appear the end of a pattern and will match anything including a slash. The matcher also ignores trailing `/` at the end of a path.
> Wildcard/pattern matching for allowed URIs

- README.md
- main.go
Hides the `allow-ip` and `verify-ip` flags, which implement checks on IP subject alternative names on certificates. Hiding these because (1) IPs on certificates are an anti-pattern, and (2) it's kinda confusing that these are checks on the certificate subject and not a network ACL of sorts. Something like `--allow-ip 127.0.0.1` could easily be misinterpreted, for example.
> Hide allow-ip/verify-ip to avoid confusion

- wildcard/matcher.go
- wildcard/matcher_test.go
Added more tests, fixed a bug in how `**` behaves (`bar/**` also matched `barf`, instead of just `bar/test`).
> Add more wildcard tests

- Dockerfile
Totally fine to reject this. Having curl in the container makes life simpler for things like running health checks in kubernetes.
> Add curl into container

- main.go
- proxy/proxy.go
- proxy/proxy_test.go
In a dynamic environment like Kubernetes, health checks
are often performed via simple TCP connections. These in
turn never complete the TLS handshake and cause a lot of
ongoing noisy errors. Allow these to be silenced.
Signed-off-by: Don Bowman <don@agilicus.com>
> Add client/server quiet flag to silence TLS errors to log

- README.md
- main.go
- tls.go
- tls_test.go
In some environments (e.g. Kubernetes cert-manager), certificates
are managed by an external process that causes them to be
not bundled, and not possible to bundle. This allows the
certificate and key to be treated separately.
Signed-off-by: Don Bowman <don@agilicus.com>
> Add keystoreKeypath for separate tls.crt/tls.key case

- .travis.yml
- Makefile
- Makefile.dist
Generates a man page when running a dist build using the `--help-man` functionality in Kingpin, and makes it so it gets uploaded to GitHub when we do a release.
> Generate man page for new releases

- Makefile
- doc.go
- main.go
Adds more help text to the man page, not as extensive as the README and other docs but gives some helpful pointers at least go get started and refers to the GitHub repo for extra documentation.
Here's what it looks like:
> Custom man page template for better help/explanation

- main.go
- tests/test-server-disable-authentication.py
Fixes #221
The TLS config property `VerifyPeerCertificate` was still being set even if the `disable-authentication` flag was set. This caused an error to be returned from the function if a client presented a client cert, as none of the verification would pass. Therefore, it was agreed in #221 that this shouldn't be configured if authentication is disabled.
It seems that the `serverListen` function in main.go isn't covered by tests and thus nor is this code path. I'd be happy to add a test for this if you point me in the right direction.
> Don't set VerifyPeerCertificate function if authentication is disabled

- .travis.yml
- certloader/pkcs11_disabled.go
- certloader/pkcs11_enabled.go
This allows opting out of PKCS11 (to avoid needing libltdl), but with CGO still
enabled so certstore is usable
It's a negative so that PKCS11 is built by default.  Maybe we don't need PKCS11 by default, and can make it a build time option like certstore?
~ CGO_ENABLED=1 go build -tags "nopkcs11 certstore"
~ otool -L ./ghostunnel
./ghostunnel:
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1570.15.0)
/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 58286.251.4)
/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
> Add a "nopkcs11" build tag

- .gitignore
- Makefile
- certloader/certstore_enabled.go
- launchd_disabled.go
- launchd_enabled.go
- main.go
This PR introduces two new features.
1. When starting ghostunnel under launchd, it's possible to have launchd provide a socket that ghostunnel can use. This behavior is provided now in launchd_enabled.go.
2. There are some corner cases with selecting a certificate that were not previously supported. These are detailed in the commit message on the third commit.
> Support for launchd and improvements for keychain/certstore certificate selection

- main.go
- main_test.go
- tests/common.py
- tests/test-client-handles-client-closes-connection-unix.py
- tests/test-mutually-exclusive-client-flags.py
Flag validation previously blocked using cert/key in client mode, fix that up and add some more tests for flag validation handling.
> Allow cert/key in client mode, fixes issue #230

- main.go
- tls.go
When in server mode, we set curve preference to make sure clients won't be able to select inefficiently implemented curves, at least for x86-64 platforms. But in client mode that argument doesn't hold, and makes ghostunnel clients incompatible with some backend services where we don't control their curve prefs. This splits the template config for client/server so we can relax the curve prefs for clients.
> Relax curve prefs in client mode; fixes issue #232

- docs/METRICS.md
- main.go
Add `/_metrics/prometheus` metrics url to make it easier to get it working in Kubernetes using Proemtheus annotations.
> Add alternative url for prometheus metrics

- status.go
- status_test.go
Without this change, `_/status` returns a JSON response with Content-Type set to `text/plain; charset=utf-8`
> Correctly set Content-Type for /_status response

- main.go
Validation for unsafe ciphers is currently broken, even if `--allow-unsafe-cipher-suites` is used it throws a `error: invalid cipher suite option: UNSAFE-AZURE` error.
> Fix unsafe cipher validation

- certloader/no_cert.go
- certloader/no_cert_test.go
GetCertificate and GetClientCertificate should always return a non-nil cert, if no cert is present an empty tls.Certificate should be used. Otherwise crypto/x509 may panic with a nil ptr deref in a TLS handshake. See #234. cc @mblaschke
> Fix issue #234

- test-keys/Makefile
There isn't any dependency on `openssl.ext` even when it's used as the input for `openssl --extfile`. When I modified `openssl.ext` to test some modifications, `test-keys` didn't re-generate properly.
This PR fixes that by adding an explicit dependency each place it's used.
> Add explicit dependency on extensions config

- test-keys/Makefile
The change introduced in the commit `396aebe83bf353e2f` broke the build
rules in the recipes, as the latter depend heavily, but not explicitly,
in the order of the prerequisites.  Thus, it is very easy for someone to
break these rules.
To make the order more explicit, I added a short notice.  Ideally, we
should not depend on such order or let make(1) figure out automatically
the correct elements.
> test-keys: fix order of prerequisites in rules

- proxy/proxy.go
We are starting to use ghostunnel for a project and we require to store an audit log (on the server) matching the subject of the certificate and the IP of the client.
The easy way is just to add it to the already existing connection log and parsing ghostunnel output.
I'm PRing it in case you find it useful/interesting.
> Add subject to connect log

- certloader/certtlsconfig.go
The returned cert is not necessarily nil, it could be a zero value.
> Fixes issue #268

- .travis.yml
- Makefile.dist
Better than having lots of small files for each binary, makes the release a bit cleaner. I did this for the v1.5.1 release to patch the recent Go CVE, this PR is the cherry-pick on master.
> Upload single sha256sums file for dist build

- main.go
- socket/net.go
- socket/net_test.go
The pull request is to address the issue https://github.com/square/ghostunnel/issues/294
By making parameter `--status` handle value like `http://127.0.0.1:8888`, `/_status` and `/_metrics` could serve via HTTP.
> Enable serving /_status and /_metrics via HTTP

- go.mod
- go.sum
go-spiffe v1.1.0 contains a small change to the handling of federated trust domain bundles that brings it in line with the Workload API specification. Without the fix, it is possible for federation to be broken with future releases of SPIRE.
> Update to go-spiffe v1.1.0

- README.md
https://github.com/ghosttunnel/certstrap doesn't exist but https://github.com/square/certstrap does
> fixes broken link

- certloader/logger.go
- certloader/spiffe_tls_config.go
- certloader/spiffe_tls_config_test.go
- doc.go
- tests/test-client-launchd-socket-activation-error.py
- tests/test-client-systemd-socket-activation-error.py
- tls_test.go
A bit more testing for failure cases, should give us better coverage for systemd/launchd error paths. Also removed the extra Logger interface in the certloader package.
> A bit more testing

- main.go
Print logs to stdout, as we should. Print error to stderr if run fails.
> Print logs to stdout

- main.go
- main_test.go
- status.go
- status_test.go
Signed-off-by: Colton J. McCurdy <mccurdyc22@gmail.com>
Addresses https://github.com/ghostunnel/ghostunnel/issues/364
```
GO_VERSION=1.17 make docker-test
```
> Adding support for a layer-7 (HTTP(S)) status endpoint

- README.md
- auth/auth.go
- auth/auth_test.go
- docs/ACCESS-FLAGS.md
- main.go
This hooks up the connect timeout flag to the OPA query timeout, cleans up the flag placeholders a bit to make help output more readable, and updates the README and ACCESS-FLAGS docs.
> Flags & docs updates

- Dockerfile
Forgot to update this when I updated the release builds in Github to Go 1.19.
> Bump Dockerfile base to Go 1.19

- certloader/spiffe_tls_config.go
- main.go
- vendor/github.com/spiffe/go-spiffe/v2/spiffetls/tlsconfig/config.go
Fixes #390 
In #390, you still had `config.ClientAuth = tls.RequireAnyClientCert` for `GetServerConfig` in place. This overrides the `NoClientCert` from `main.go`.
`--disable-authentication` on the `server` is currently fully disabling client authentication by applying `config.ClientAuth = tls.NoClientCert`. Using `tls.RequestClientCert` would at least allow to show the certificate (if optionally provided).
The client still didn't allow to enable `--disable-authentication`, since the `hasValidCredentials` was containing it. I therefore refactored the check.
It now fully works with SPIFFE as expected. You might want to test again if all other use-cases work as well with `config.ClientAuth = tls.RequestClientCert`. The tests all passed.
> Support disable-authentication on client and server with SPIFFE

- .github/workflows/test.yml
Update codecov action to v3
The v1 action is deprecated, as is the underlying bash script it uses.
> Update codecov github action

- Dockerfile-test
Fixes the linux integration tests CI job.
Here's an example of the failing test: https://github.com/ghostunnel/ghostunnel/actions/runs/5469132117/jobs/9957675360#step:3:57
```
Package netcat is a virtual package provided by:
netcat-openbsd 1.219-1
netcat-traditional 1.10-47
E: Package 'netcat' has no installation candidate
```
At some point, the netcat package must have been remove/renamed. 
Let me know if you'd prefer `netcat-openbsd` or `netcat-traditional`!
> test: use netcat-traditional in integration test Docker image

- .github/workflows/release.yml
Fix steps to upload assets on tagged release. The Windows release upload step needs to deal with the "exe" suffix.
> Fix steps to upload assets on tagged release

- main.go
Pass disableAuth as an argument instead of using the flag in getTLSConfigSource. This function is used both in client and server mode, and we need to use the appropriate value for the mode we're in.  Fixes #417.
> Pass disableAuth as an argument instead of using flag

- .github/workflows/compile.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- Makefile
- README.md
> Upgrade to Go 1.22

- certstore/certstore_darwin.go
Avoid use of deprecated SecTrustGetCertificateAtIndex. Replaces #420.
> Avoid use of deprecated SecTrustGetCertificateAtIndex

- .github/workflows/compile.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Update Github actions to new versions:
* checkout@v2 to checkout@v4
* setup-go@v2 to setup-go@v5
* codecov-action@v3 to codecov-action@v4
> Update Github actions to new versions

- .github/workflows/test.yml
Skip Codecov upload on Dependabot PRs. Dependabot doesn't have access to the token required for upload, so it fails every time. But we don't need coverage information when updating dependencies anyway so let's skip it.
> Skip Codecov upload on Dependabot PRs

- main.go
Fix nil ptr deref on Windows/Linux when keychain flags are used.
The panic comes from line 67 in `tls.go`:
```
if hasKeychainIdentity() {
logger.Printf("using operating system keychain as certificate source")
return certloader.CertificateFromKeychainIdentity(*keychainIdentity, *keychainIssuer, caBundlePath, *keychainRequireToken)
}
```
Flag `keychainRequireToken` can't be nil, even if it's not supported on Windows/Linux.
> Fix nil ptr deref on Windows/Linux when keychain flags are used

- certstore/certstore_windows.go
Support for RSA-PSS on Windows was merged in 23108a63, but this line of code was never updated.
> Windows implementation supports RSA-PSS

- certstore/certstore_windows.go
(1) The `certstore` module supports two backends on Windows, CAPI and CNG. Support for RSA-PSS on CNG was previously added in 23108a6373dbec25cce94a710abe88625b264c84, though was not functional until #459. However, the change in #459 removed the check for RSA-PSS for both the CAPI and CNG code paths, even though RSA-PSS was only supported in CNG. This change should fix the issue by returning an error if RSA-PSS is used on CAPI keys.  
(2) The CNG implementation for RSA-PSS did not check for `PSSSaltLengthAuto` on `rsa.PSSOptions`. This meant that `saltLen` passed to CNG was set to 0 when the caller specified auto. To fix this, we set the salt length to the digest length if auto is specified.
> Fix Windows unit test error relating to RSA-PSS on CAPI keys

- main.go
- signals.go
- tests/test-client-shutdown-http.py
- tests/test-client-shutdown-sigterm.py
- tests/test-server-shutdown-http.py
- tests/test-server-shutdown-sigterm.py
- tests/test-server-shutdown-timeout.py
When running as a sidecar container in Kubernetes to jobs, the primary container needs a way to signal to the other containers they should also terminate. Although you can share the process namespace, this is simpler to achieve since you don't have to look for the correct PID.
I also tweaked the sigterm tests to only TERM once and without an open connection since while working on the HTTP tests (which were modeled after those) the server was reaching the timeout because of the open connection which is already covered in the timeout tests.
> Add optional /_shutdown endpoint for terminating via HTTP POST

- certloader/certstore_disabled.go
- certloader/certstore_enabled.go
- certloader/certstore_test.go
- certloader/pkcs11_enabled.go
- certloader/pkcs11_test.go
- certstore/certstore.go
- certstore/certstore_darwin.go
- certstore/certstore_linux.go
- certstore/certstore_windows.go
- certstore/main_test.go
- main.go
- tls.go
- tls_test.go
Add support for LOCAL_MACHINE and CURRENT_SERVICE keychains on Windows, because we might want to load our identities from there. We still prefer the CURRENT_USER keystore first and foremost. Also, this change adds additional logging for the certstore module.
Work in progress -- opening this up here so I can run Windows tests on Github.
> Windows: Support LOCAL_MACHINE and CURRENT_SERVICE

- .github/workflows/compile.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Fetch tags when checking out code in Github Actions. This is necessary for "git describe" to work correctly on builds, so that "ghostunnel --version" can show the proper version and not just the revision.
> Fetch tags when checking out code in Github Actions

- Makefile
- tests/common.py
- tests/test-client-shutdown-http.py
- tests/test-client-status-port.py
- tests/test-server-metrics-endpoint.py
- tests/test-server-quiet-all-logs.py
- tests/test-server-quiet-conn-logs.py
- tests/test-server-shutdown-http.py
- tests/test-server-status-port.py
- tests/test-server-tls-handshake-timeout.py
Fix integration tests for Python 3.12:
* ssl.wrap_socket is now part of ssl.SSLContext
* Python is now pickier about extensions on root certs
* urlopen needs a context to set CA certs
> Fix integration tests for Python 3.12

- landlock_linux.go
- landlock_test.go
Fix broken landlock TCP rules generation, which was not correctly distinguishing between bind and connect rules. Not clear why this worked previously, but I'm thinking it was due to a bug with networking support in go-landlock (there were some fixes included that repo in the past ~6 months since we implemented this).
> Fix broken landlock TCP rules generation

- .github/workflows/compile.yml
- .github/workflows/docker.yml
- .github/workflows/release.yml
Fix broken release workflow checkout action. Params need to be set using "with".
See https://github.com/actions/checkout
> Fix broken release workflow checkout action

- .github/workflows/docker.yml
- .github/workflows/release.yml
Avoid fetch-tags in checkout since it breaks when triggered from tag
> Avoid fetch-tags in checkout since it breaks when triggered from tag

- .github/workflows/release.yml
- Makefile
Proper version detection for GH release action, because "git describe" doesn't seem to work reliably in GH actions (even with fetch-depth being 0 the release tag isn't found and described correctly). We can use GITHUB_REF_NAME instead. Also clean up unused Makefile target.
> Proper version detection for GH release action

- main.go
Use the connect timeout flag to set the read header timeout for the status HTTP server. This is an internal status endpoint, but it doesn't hurt to set the timeout here anyway.
> Set read header timeout for the status HTTP server

- .github/workflows/compile.yml
- .github/workflows/docker.yml
- .github/workflows/lint.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- README.md
Fixes https://github.com/ghostunnel/ghostunnel/issues/528. Creating release builds on older versions of Ubuntu allows us to maintain compatibility with older versions of GLIBC for longer, making the official release binaries more universal. For compiling and testing, we use both old and new versions of Ubuntu.
> Pin Github Actions Ubuntu image versions, update README accordingly

- .github/dependabot.yml
Having it run weekly is a bit too spammy/noisy for my liking, especially with the copious amounts of GRPC etc. releases.
> Update dependabot to monthly schedule

- .github/workflows/compile.yml
- .github/workflows/docker.yml
- Dockerfile-alpine
- Dockerfile-debian
Provide Debian-based Docker image, alongside Alpine. Some folks may prefer Debian (glibc) instead of Alpine (musl) as their base image. We also add a new build job in `compile.yml` to build the Docker images on pull requests, not just after merge.
> Provide Debian-based Docker image

- proxy/proxy.go
- proxy/str.go
- proxy/str_test.go
Changes:
- Log bytes sent, received, and conn open time
- Ignore more closed connection errors (not just on "read") -- don't think these were useful
Example client log:
```
[39263] 2025/02/09 14:24:54.102740 starting ghostunnel in client mode
[39263] 2025/02/09 14:24:54.103382 using keystore file on disk as certificate source
[39263] 2025/02/09 14:24:54.104632 using target address localhost:8003
[39263] 2025/02/09 14:24:54.104998 listening for connections on localhost:8002
[39263] 2025/02/09 14:24:59.126954 opening pipe: tcp:127.0.0.1:57372 [no tls] <-> tcp:127.0.0.1:8003 [CN=server]
[39263] 2025/02/09 14:25:00.635175 closed pipe: tcp:127.0.0.1:57372 [no tls] <-> tcp:127.0.0.1:8003 [CN=server] [forwarded 398.3 KiB, returned 0 bytes, open 1.508188167s]
```
Example server log:
```
[39265] …
```
> Improve proxy logging

- main.go
- main_test.go
- proxy/benchmark_test.go
- proxy/proxy.go
- proxy/proxy_test.go
- proxy/str.go
- tests/common.py
- tests/test-client-handles-client-closes-connection-unix.py
- tests/test-client-handles-client-closes-connection.py
- tests/test-client-handles-server-closes-connection-unix.py
- tests/test-client-handles-server-closes-connection.py
- tests/test-server-handles-client-closes-connection-unix.py
- tests/test-server-handles-client-closes-connection.py
- tests/test-server-handles-server-closes-connection-unix.py
- tests/test-server-handles-server-closes-connection.py
- tests/test-server-max-conn-lifetime.py
Improvements to the core proxy package:
* Set up a pool of reusable buffers to reduce allocations
* Close only corresponding read, write side of connection when copying data
* Set deadline (via configurable timeout) for max conn lifetime after other side closes
* New flag for setting max conn lifetime regardless of circumstances (defaults to zero)
* Add benchmarks for the proxy package to test allocs
Before this change:
```
goos: darwin
goarch: arm64
pkg: github.com/ghostunnel/ghostunnel/proxy
cpu: Apple M1
BenchmarkCopyData/1_bytes-8         	  155918	      6713 ns/op	   36730 B/op	      31 allocs/op
BenchmarkCopyData/2_bytes-8         	  158008	      6809 ns/op	   36731 B/op	      31 allocs/op
BenchmarkCopyData/4_bytes-8         	  175996	      6766 ns/op	   36733 B/op	      31 …
```
> Improve proxy performance and connection handling

- README.md
- docs/ACCESS-FLAGS.md
- docs/ACME.md
- docs/KEYCHAIN.md
- docs/MANPAGE.md
- docs/METRICS.md
- docs/SOCKET-ACTIVATION.md
Add additional documentation. Expands on a couple of topics, adds the man page in Markdown format, and cleans up some of the paragraphs in the main README.
> Add additional documentation

- main.go
- proxy/proxy.go
- status.go
- status_test.go
Adds the listening & forward addresses to the status line in systemd, and in the status endpoint. This should help distinguish different ghostunnel processes from each other, if there's more than one running on a machine. 
Example for systemd (status now shows better info):
```
● ghostunnel.service - Ghostunnel
Loaded: loaded (/etc/systemd/system/ghostunnel.service; disabled; preset: enabled)
Active: active (running) since Fri 2025-03-28 15:54:47 PDT; 1 day 23h ago
Main PID: 7945 (ghostunnel)
Status: "listening | server proxying localhost:9443 => localhost:9080"
Tasks: 10 (limit: 18907)
Memory: 10.4M (peak: 12.0M)
CPU: 6min 52.654s
```
Example output of status endpoint:
```
{
"ok": false,
"status": "critical",
"listen_address": "localhost:9443",
"forward_address": "localhost:9080", …
```
> Show a bit more information in status line/endpoint

- proxy/proxy_test.go
Bump timeouts to make Windows tests less flaky (specifically TestMaxConcurrentConns)
> Bump timeouts to make Windows tests less flaky

- main.go
Hide the --cipher-suites flag. Per #34, the order is now ignored anyway, and for TLS 1.3 it's not configurable. Let's hide it and mark it deprecated but otherwise leave the functionality intact (for now).
> Hide the --cipher-suites flag

- main.go
Set default close timeout to 1s, closer to old behavior. (Old behavior was equivalent to 0s)
> Set default close timeout to 1s, closer to old behavior
